# Generated by Django 4.2.6 on 2023-10-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
